sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
  - npm install
script:
  - docker build -t teams .
deploy:
  provider: script
  cleanup: true
  script:
    heroku container:login;
    heorku container:push web -a $HEROKU_APP_NAME;
    heorku container:release web -a $HEROKU_APP_NAME;
  branch: master
